frontend:
  image: codeforpoznan/volontulo
  # build: .
  entrypoint: ng serve --open --host=0.0.0.0
  # entrypoint: tail -f /dev/null
  # entrypoint: npm run ssr
  working_dir: /volontulo/frontend
  ports:
    - 4200:4200
  links:
    - backend:backend
  volumes:
    - ./frontend:/volontulo/frontend
    - /volontulo/frontend/node_modules

backend:
  image: codeforpoznan/volontulo
  # build: .
  entrypoint: bash docker-entrypoint.sh
  # entrypoint: tail -f /dev/null
  working_dir: /volontulo/backend
  environment:
    DJANGO_SETTINGS_MODULE: volontulo_org.settings.dev
    VOLONTULO_SECRET_KEY: a63eb5ef-3b25-4595-846a-5d97d99486f0
    VOLONTULO_DB_HOST: db
    VOLONTULO_DB_PASS: volontulo
  ports:
    - 8000:8000
  links:
    - db:db
  volumes:
    - ./backend:/volontulo/backend
    - /volontulo/backend/apps/volontulo/node_modules

db:
  image: postgres
  environment:
    POSTGRES_DB: volontulo
    POSTGRES_USER: volontulo
    POSTGRES_PASSWORD: volontulo
